### ISSUE TITLE
Disappearing settings UI issue

### ISSUE THREAD

**Issue by alehandrof** [edalzell/statamic-akismet#1]
I came across a UI issue in this addon's settings that's easier to show than explain:

![2018-08-27 18 20 46](https://user-images.githubusercontent.com/1588449/44669176-e0fe2a80-aa27-11e8-9afe-f7369117f8ce.gif)

**Comment by edalzell** [comment]
bah I was hoping no one would find that...it's a Statamic issue that's a pain to work around.

**Comment by edalzell** [comment]
For my own reference, here is the Statamic issue: https://github.com/statamic/v2-hub/issues/1373

**Comment by edalzell** [comment]
@alehandrof what version of Akismet? What version of Statamic?

**Comment by alehandrof** [comment]
- Statamic: 2.10.3
- Akismet 1.6

**Comment by edalzell** [comment]
Won't fix, please check on current version of Akismet, which supports Statamic v3.
