### ISSUE TITLE
What are the privacy terms with respect how it handles your data within form submissions - does it pass any data to any 3rd parties?

### ISSUE THREAD

**Issue by FlyDuo** [edalzell/statamic-akismet#13]
For this type of addon, it's likely going to be used in contact + other user submission forms which brings up some concerns around privacy and data collection.

**With respect to how they handle/respect user data in form submissions its examining for spam:**
1. What are the privacy terms for the Akismet addon?
1.  What are the privacy terms for Akismet (the service by Automattic) 

Do any 3rd party entities have access to any of the data that's been examined/processed by the Akismet addon or Akismet service? 

**Depending on how the data is handled:** 
1. How is the data being collected?
1. Where is the data stored?
1. How long is it stored?
1. How is it protected?
1. Does Akismet the addon or Akismet the Automattic company/service support disabling access/preventing 3rd party access to any/all of the form data?
1. Who has access to the data?
1. What data exactly do they have access to?
1. Are there mechanisms to remove the data after its been collected?

Thanks,
Reuben

**Comment by edalzell** [comment]
How does [this](https://github.com/edalzell/statamic-akismet/blob/master/PRIVACY.md) look @FlyDuo?
