### ISSUE TITLE
The verify-key endpoint should only be called once.

### ISSUE THREAD

**Issue by cfinke** [edalzell/statamic-akismet#14]
While preparing to add this to our list of Akismet libraries (https://akismet.com/development/api/#use-a-library), I noticed that you're calling the `isKeyValid()` method before every call to `submit-spam`, `submit-ham`, and `comment-check`, which itself calls the `verify-key` API endpoint.

This endpoint only needs to be called once, when the user first enters their API key, to ensure that it is valid.  From that point on, you can just call the other endpoints with the key without first re-checking that it is valid. (If it's not valid, the other endpoints will return the text `invalid`).

**Comment by edalzell** [comment]
Ah thanks, I’ll adjust.

**Comment by edalzell** [comment]
Updated in latest version @cfinke, here : https://github.com/silentzco/statamic-akismet
