### ISSUE TITLE
Ensure that submit-spam and submit-ham endpoints are only called when Akismet was wrong.

### ISSUE THREAD

**Issue by cfinke** [edalzell/statamic-akismet#3]
I'm not familiar with Statamic or how Statamic addons work, but a common mistake made by developers when they write an integration with Akismet's API is to send *all* ham to the `submit-ham` endpoint and *all* spam to `submit-spam`. These endpoints should only be used when Akismet got the initial decision wrong; e.g., if you mark something as spam when Akismet said it was ham, it should be sent to the `submit-spam` endpoint, and vice versa.

I'm not saying you implemented this wrong; I can't tell exactly since I've never used Statamic, but I just wanted to make a note of it.

**Comment by edalzell** [comment]
yup that's what I do.
