### ISSUE TITLE
Spam entries not showing in control panel

### ISSUE THREAD

**Issue by jeremydouglas** [edalzell/statamic-akismet#4]
I have upgraded a couple sites to Statamic 2.10.7 with Akismet running on 1.6.3. These sites aren't showing the spam results in the listing page: `/cp/addons/akismet/queue?form=contact`

@edalzell can you reproduce this?

<img width="670" alt="cp-akismet" src="https://user-images.githubusercontent.com/113216/47503416-119bee00-d838-11e8-9ba7-25056d8ea27f.png">

**Comment by jeremydouglas** [comment]
This is working locally on my Mac, but not in production. PHP is version 7.2.

**Comment by edalzell** [comment]
I wonder if it's a case sensitivity thing?

What does this folder look like in production vs local: https://cl.ly/638d305e025d

**Comment by jeremydouglas** [comment]
The `Akismet` folder is uppercase in both instances.

**Comment by edalzell** [comment]
And there are files in there?

**Comment by jeremydouglas** [comment]
Yes, there are.

<img width="1140" alt="production-screenshot" src="https://user-images.githubusercontent.com/113216/47787144-56b29b00-dce4-11e8-834d-318295d65057.png">

I can send you files if it helps.

**Comment by edalzell** [comment]
can you send me your whole `site` folder? Feel free to email, erin@silentzconsulting.com.

**Comment by edalzell** [comment]
Great news, I can duplicate this locally @jeremydouglas.

Investigating.

**Comment by edalzell** [comment]
Found it, you were missing the `site/addons/Akismet/resources/assets` folder. Added it in and it works.

Perhaps it is git ignored @jeremydouglas

**Comment by jeremydouglas** [comment]
Yes, the `assets` line in my gitignore is too global :(

Thanks for that @edalzell
